export class ErrorRespons {
  status: string = 'FAILURE';
  message: string = '';
  item?: any = {};
  error: any = {};
}

export enum ErrorRes {
  INVALIDUSER = 'INVALIDUSER',
  BADREQUEST = 'BADREQUEST',
  DELETEREQUESTFAILED = 'DELETEREQUESTFAILED',
  INVALIDUSERCREDENTIAL = 'INVALIDUSERCREDENTIAL',
  SESSIONINVALID = 'SESSIONINVALID',
  SESSIONEXPIRED = 'SESSIONEXPIRED',
  EMAILALREADYTAKEN = 'EMAILALREADYTAKEN',
}
/*

= 'INVALID USER',
= 'BADREQUEST',
= 'DELETEREQUESTFAILED',
= 'INVALID USER CREDENTIAL',
= 'SESSION INVALID',
= 'SESSION EXPIRED',
= 'EMAIL ALREADY TAKEN',
*/
